/* Auto-generated — run: node scripts/generate-lucide-shim.mjs */
import React, { forwardRef, type ComponentType, type SVGProps } from 'react';
import { Lineicons } from '@lineiconshq/react-lineicons';
import * as LI from '@lineiconshq/free-icons';
import * as Lucide from '__lucide_fallback__';

export type LucideIcon = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string }>;
export type LucideProps = SVGProps<SVGSVGElement> & { size?: number | string };

function fromLine(icon: (typeof LI)[keyof typeof LI], displayName: string) {
  const C = forwardRef<SVGSVGElement, LucideProps>(({ size = 24, className, color, strokeWidth, ...rest }, ref) => (
    <Lineicons ref={ref} icon={icon} size={size} className={className} color={color} strokeWidth={strokeWidth} {...rest} />
  ));
  C.displayName = displayName;
  return C;
}

export const ArrowLeft = fromLine(LI.ArrowLeftOutlined, 'ArrowLeft');
export const ArrowRight = fromLine(LI.ArrowRightOutlined, 'ArrowRight');
export const ArrowUp = fromLine(LI.ArrowUpwardOutlined, 'ArrowUp');
export const Award = fromLine(LI.Trophy1Outlined, 'Award');
export const BadgeCheck = fromLine(LI.CheckCircle1Outlined, 'BadgeCheck');
export const Bell = fromLine(LI.Bell1Outlined, 'Bell');
export const Bookmark = fromLine(LI.Bookmark1Outlined, 'Bookmark');
export const BookmarkCheck = fromLine(LI.Bookmark1Outlined, 'BookmarkCheck');
export const Briefcase = fromLine(LI.Briefcase1Outlined, 'Briefcase');
export const Building = fromLine(LI.Buildings1Outlined, 'Building');
export const Building2 = fromLine(LI.Buildings1Outlined, 'Building2');
export const Calendar = fromLine(LI.CalendarDaysOutlined, 'Calendar');
export const Camera = fromLine(LI.Camera1Outlined, 'Camera');
export const Check = fromLine(LI.CheckOutlined, 'Check');
export const CheckCircle = fromLine(LI.CheckCircle1Outlined, 'CheckCircle');
export const CheckCircle2 = fromLine(LI.CheckCircle1Outlined, 'CheckCircle2');
export const ChevronDown = fromLine(LI.ChevronDownOutlined, 'ChevronDown');
export const ChevronLeft = fromLine(LI.ChevronLeftOutlined, 'ChevronLeft');
export const ChevronUp = fromLine(LI.ChevronUpOutlined, 'ChevronUp');
export const Chrome = fromLine(LI.ChromeOutlined, 'Chrome');
export const Database = fromLine(LI.Database2Outlined, 'Database');
export const DollarSign = fromLine(LI.DollarOutlined, 'DollarSign');
export const Download = fromLine(LI.Download1Outlined, 'Download');
export const Edit = fromLine(LI.Pencil1Outlined, 'Edit');
export const Edit2 = fromLine(LI.Pencil1Outlined, 'Edit2');
export const Edit3 = fromLine(LI.Pencil1Outlined, 'Edit3');
export const Eye = fromLine(LI.EyeOutlined, 'Eye');
export const Facebook = fromLine(LI.FacebookOutlined, 'Facebook');
export const File = fromLine(LI.FileMultipleOutlined, 'File');
export const FileText = fromLine(LI.FileMultipleOutlined, 'FileText');
export const FileX = fromLine(LI.FileXmarkOutlined, 'FileX');
export const Filter = fromLine(LI.Funnel1Outlined, 'Filter');
export const Flag = fromLine(LI.Flag1Outlined, 'Flag');
export const Gamepad2 = fromLine(LI.DiscordOutlined, 'Gamepad2');
export const Github = fromLine(LI.GithubOutlined, 'Github');
export const Globe = fromLine(LI.Globe1Outlined, 'Globe');
export const Heading1 = fromLine(LI.TextFormatOutlined, 'Heading1');
export const Heading2 = fromLine(LI.TextFormatOutlined, 'Heading2');
export const Heart = fromLine(LI.HeartOutlined, 'Heart');
export const Home = fromLine(LI.Home2Outlined, 'Home');
export const Image = fromLine(LI.PhotosOutlined, 'Image');
export const Instagram = fromLine(LI.InstagramOutlined, 'Instagram');
export const Linkedin = fromLine(LI.LinkedinOutlined, 'Linkedin');
export const Loader = fromLine(LI.Spinner3Outlined, 'Loader');
export const Loader2 = fromLine(LI.Spinner3Outlined, 'Loader2');
export const LogIn = fromLine(LI.EnterOutlined, 'LogIn');
export const LogOut = fromLine(LI.ExitOutlined, 'LogOut');
export const Mail = fromLine(LI.Envelope1Outlined, 'Mail');
export const MapPin = fromLine(LI.MapMarker1Outlined, 'MapPin');
export const Menu = fromLine(LI.MenuHamburger1Outlined, 'Menu');
export const Mic = fromLine(LI.Microphone1Outlined, 'Mic');
export const Minus = fromLine(LI.MinusOutlined, 'Minus');
export const Moon = fromLine(LI.MoonHalfRight5Outlined, 'Moon');
export const MoreHorizontal = fromLine(LI.MenuMeatballs1Outlined, 'MoreHorizontal');
export const Pencil = fromLine(LI.Pencil1Outlined, 'Pencil');
export const Plus = fromLine(LI.PlusOutlined, 'Plus');
export const Search = fromLine(LI.Search1Outlined, 'Search');
export const Send = fromLine(LI.TelegramOutlined, 'Send');
export const Settings = fromLine(LI.Gear1Outlined, 'Settings');
export const Share2 = fromLine(LI.Share1Outlined, 'Share2');
export const Shield = fromLine(LI.Shield2Outlined, 'Shield');
export const ShieldCheck = fromLine(LI.Shield2CheckOutlined, 'ShieldCheck');
export const ShieldOff = fromLine(LI.Shield2Outlined, 'ShieldOff');
export const Sliders = fromLine(LI.SlidersHorizontalSquare2Outlined, 'Sliders');
export const SlidersHorizontal = fromLine(LI.SlidersHorizontalSquare2Outlined, 'SlidersHorizontal');
export const Smile = fromLine(LI.EmojiSmileOutlined, 'Smile');
export const Star = fromLine(LI.StarFatOutlined, 'Star');
export const ThumbsUp = fromLine(LI.ThumbsUp3Outlined, 'ThumbsUp');
export const Ticket = fromLine(LI.Ticket1Outlined, 'Ticket');
export const Trash2 = fromLine(LI.Trash3Outlined, 'Trash2');
export const TrendingDown = fromLine(LI.TrendDown1Outlined, 'TrendingDown');
export const TrendingUp = fromLine(LI.TrendUp1Outlined, 'TrendingUp');
export const Trophy = fromLine(LI.Trophy1Outlined, 'Trophy');
export const Twitter = fromLine(LI.XOutlined, 'Twitter');
export const Upload = fromLine(LI.Upload1Outlined, 'Upload');
export const User = fromLine(LI.User4Outlined, 'User');
export const Users = fromLine(LI.UserMultiple4Outlined, 'Users');
/** Close / dismiss — not the X (Twitter) brand; use `Twitter` for social. */
export const X = Lucide.X;
export const XCircle = fromLine(LI.XmarkCircleOutlined, 'XCircle');
export const Youtube = fromLine(LI.YoutubeOutlined, 'Youtube');
export const Zap = fromLine(LI.Bolt2Outlined, 'Zap');
export const Activity = Lucide.Activity;
export const AlertCircle = Lucide.AlertCircle;
export const AlertTriangle = Lucide.AlertTriangle;
export const Archive = Lucide.Archive;
export const ArrowRightLeft = Lucide.ArrowRightLeft;
export const AtSign = Lucide.AtSign;
export const Ban = Lucide.Ban;
export const BarChart3 = Lucide.BarChart3;
export const BellOff = Lucide.BellOff;
export const Bold = Lucide.Bold;
export const ChevronRight = Lucide.ChevronRight;
export const Clock = Lucide.Clock;
export const Cloud = Lucide.Cloud;
export const Code = Lucide.Code;
export const Code2 = Lucide.Code2;
export const Command = Lucide.Command;
export const Compass = Lucide.Compass;
export const Copy = Lucide.Copy;
export const Crown = Lucide.Crown;
export const ExternalLink = Lucide.ExternalLink;
export const EyeOff = Lucide.EyeOff;
export const Flame = Lucide.Flame;
export const Grid3x3 = Lucide.Grid3x3;
export const GripVertical = Lucide.GripVertical;
export const Hash = Lucide.Hash;
export const HelpCircle = Lucide.HelpCircle;
export const Info = Lucide.Info;
export const Italic = Lucide.Italic;
export const Layout = Lucide.Layout;
export const LayoutGrid = Lucide.LayoutGrid;
export const Link = Lucide.Link;
export const Link2 = Lucide.Link2;
export const List = Lucide.List;
export const ListOrdered = Lucide.ListOrdered;
export const Lock = Lucide.Lock;
export const Megaphone = Lucide.Megaphone;
export const MessageCircle = Lucide.MessageCircle;
export const MessageSquare = Lucide.MessageSquare;
export const MoreVertical = Lucide.MoreVertical;
export const Quote = Lucide.Quote;
export const Radio = Lucide.Radio;
export const Save = Lucide.Save;
export const Server = Lucide.Server;
export const Smartphone = Lucide.Smartphone;
export const Sparkles = Lucide.Sparkles;
export const Sun = Lucide.Sun;
export const Table = Lucide.Table;
export const Target = Lucide.Target;
export const ToggleLeft = Lucide.ToggleLeft;
export const ToggleRight = Lucide.ToggleRight;
export const Unlock = Lucide.Unlock;
export const UserCheck = Lucide.UserCheck;
export const UserPlus = Lucide.UserPlus;
export const UserX = Lucide.UserX;
export const Video = Lucide.Video;
export const Wallet = Lucide.Wallet;

const __default = Lucide;
export default __default;
